### ISSUE TITLE
Modification of our launchers needed

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/ms-office-online-launcher#2]
When I start the launcher from the shared folder I've a working result:

```
phil@development ~/dev/git/manjaro/basic/ms-office-online-launcher $ /usr/share/ms-office/office/ms-office-online
Identifying User Agent as - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Safari/605.1.15
```

However, if I launch it as a symlink from '/usr/bin' it fails:

```
phil@development ~/dev/git/manjaro/basic/ms-office-online-launcher $ ms-office
Identifying User Agent as - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Safari/605.1.15
Traceback (most recent call last):
  File "/usr/bin/ms-office", line 53, in <module>
    applicationWindow()
  File "/usr/bin/ms-office", line 49, in __init__
    self.webview.load_uri(settings("app", "route"))
TypeError: Argument 1 does not allow None as a value
```
Therefore we have to rethink the concept of the launcher a little.

**Comment by philmmanjaro** [comment]
Current PKGBUILD

```
# Maintainer: Philip Müller <philm@manjaro.org>
# Contributor: Vitor Lopes <vmnlop@gmail.com>

pkgname=('ms-office-online')
pkgver=18.04.1
pkgrel=4
pkgdesc="Microsoft Office Suite Online for Manjaro Linux"
url="https://www.office.com/"
depends=('python-jade-application-kit>=0.36')
license=('GPL3' 'custom')
arch=('any')
provides=('microsoft-office-online' 'microsoft-office')
source=("${pkgname}-${pkgver}-${pkgrel}.tar.gz::https://github.com/manjaro/${pkgname}-launcher/archive/${pkgver}.tar.gz"
        'authors.patch::https://github.com/manjaro/ms-office-online-launcher/commit/602d1d96500874c5ea44727bdbf1fb1691b49e05.patch'
        'makefile.patch::https://github.com/manjaro/ms-office-online-launcher/commit/c3c9a487b614e6e4264823b89fb6d5bbfd4dedee.patch'
        'makefile1.patch::https://github.com/manjaro/ms-office-online-launcher/commit/c02570df5862e13690f482640d25b8eb8abe4bf7.patch'
        'makefile2.patch::https://github.com/manjaro/ms-office-online-launcher/commit/9c7ebc13e8d7e77aa76efdc5be28964238504181.patch'
        'makefile3.patch::https://github.com/manjaro/ms-office-online-launcher/commit/6a37272d33d62a1b13b2ae5a0d71d65cfe6b12a4.patch')
sha256sums=('f7bc899379fa4999ed2b2d74b0a6db375018f42c625cb557b9885a20a5f61e8a'
            '58d71349b221791cda7887416959a7138452e7f0043805d1421b674a45afa50a'
            '067a29c1152bc6d12cb150515a5640e79aca36ebae4131b32f32fa5b01853bdc'
            '4b62679b9d8e859248a844b5832cddcea060e53c973a19916a4fef9f659f68ba'
            '6b6b87503aa437234048d60a9e4633c05e74ee129a2071ea629a6ee32c466874'
            '6cb96005ac2b6a848447b1ed1390d048e5f25a99816b6e5f2762bb9042fe4566')

prepare() {
    cd "${pkgname}-launcher-${pkgver}"
    patch -p1 -i "$srcdir"/authors.patch
    patch -p1 -i "$srcdir"/makefile.patch
    patch -p1 -i "$srcdir"/makefile1.patch
    patch -p1 -i "$srcdir"/makefile2.patch
    patch -p1 -i "$srcdir"/makefile3.patch
}

package() {
    cd "${pkgname}-launcher-${pkgver}"
    make PREFIX="/usr" DESTDIR="$pkgdir" install
}
```

**Comment by philmmanjaro** [comment]
Current package layout:

```
phil@development ~ $ pacman -Ql ms-office-online
ms-office-online /usr/
ms-office-online /usr/bin/
ms-office-online /usr/bin/ms-excel
ms-office-online /usr/bin/ms-office
ms-office-online /usr/bin/ms-onenote
ms-office-online /usr/bin/ms-outlook
ms-office-online /usr/bin/ms-powerpoint
ms-office-online /usr/bin/ms-skype
ms-office-online /usr/bin/ms-word
ms-office-online /usr/share/
ms-office-online /usr/share/applications/
ms-office-online /usr/share/applications/Excel.desktop
ms-office-online /usr/share/applications/MSOffice.desktop
ms-office-online /usr/share/applications/OneNote.desktop
ms-office-online /usr/share/applications/Outlook.desktop
ms-office-online /usr/share/applications/PowerPoint.desktop
ms-office-online /usr/share/applications/WebSkype.desktop
ms-office-online /usr/share/applications/Word.desktop
ms-office-online /usr/share/icons/
ms-office-online /usr/share/icons/hicolor/
ms-office-online /usr/share/icons/hicolor/1024x1024/
ms-office-online /usr/share/icons/hicolor/1024x1024/apps/
ms-office-online /usr/share/icons/hicolor/1024x1024/apps/ms-excel.png
ms-office-online /usr/share/icons/hicolor/1024x1024/apps/ms-office.png
ms-office-online /usr/share/icons/hicolor/1024x1024/apps/ms-onenote.png
ms-office-online /usr/share/icons/hicolor/1024x1024/apps/ms-outlook.png
ms-office-online /usr/share/icons/hicolor/1024x1024/apps/ms-powerpoint.png
ms-office-online /usr/share/icons/hicolor/1024x1024/apps/ms-skype.png
ms-office-online /usr/share/icons/hicolor/1024x1024/apps/ms-word.png
ms-office-online /usr/share/ms-office/
ms-office-online /usr/share/ms-office/excel/
ms-office-online /usr/share/ms-office/excel/ms-office-online
ms-office-online /usr/share/ms-office/excel/settings.json
ms-office-online /usr/share/ms-office/office/
ms-office-online /usr/share/ms-office/office/ms-office-online
ms-office-online /usr/share/ms-office/office/settings.json
ms-office-online /usr/share/ms-office/onenote/
ms-office-online /usr/share/ms-office/onenote/ms-office-online
ms-office-online /usr/share/ms-office/onenote/settings.json
ms-office-online /usr/share/ms-office/outlook/
ms-office-online /usr/share/ms-office/outlook/ms-office-online
ms-office-online /usr/share/ms-office/outlook/settings.json
ms-office-online /usr/share/ms-office/powerpoint/
ms-office-online /usr/share/ms-office/powerpoint/ms-office-online
ms-office-online /usr/share/ms-office/powerpoint/settings.json
ms-office-online /usr/share/ms-office/skype/
ms-office-online /usr/share/ms-office/skype/ms-office-online
ms-office-online /usr/share/ms-office/skype/settings.json
ms-office-online /usr/share/ms-office/word/
ms-office-online /usr/share/ms-office/word/ms-office-online
ms-office-online /usr/share/ms-office/word/settings.json
```

**Comment by codesardine** [comment]
This is related with JAK as it uses the launcher path to search for the settings file.

JAK line 27 - options.route = os.path.dirname(os.path.abspath(sys.argv[0])) 
At the moment i don't have a better way of doing this.
workaround:
   create a shell script in bin /usr/share/ms-office/office/ms-office-online

**Comment by philmmanjaro** [comment]
Well, if this is the case we have to modifiy our launcher, which calls JAK. For now you do this in line 12 of the launcher: `os.chdir(os.path.dirname(os.path.realpath(__file__)))`. This will logically change to `/usr/bin`, as this is the location of the file we called. Then we have another section which is never used (line 38 - 42):

```
                else:
                    # use existing office settings.json
                    os.chdir("/usr/share/ms-office/msoffice/")
                    # open url in a new window
                    subprocess.call(["jak", url])
```

With the new way we install to `/usr/share/ms-office/office`. `office` may also be `word` or `skype` and so on. So, the hardcoded path might not work anyway.

To resolve it, it would be good to have an option to tell JAK where the settings file is located at. For now I'm using a workaround already by using a bash script in `/usr/bin` calling the python-app in `/usr/share/ms-office/<app>`.

**Comment by codesardine** [comment]
for example if you remove www.skype.com from "same_frame" skype will open in a separate application window as i think it should since is a separate application, any clicked link  if it is not in same_frame will open in a separate window, some users mention that links were not working so I implemented this.

**Comment by codesardine** [comment]
fixed https://github.com/codesardine/Jade-Application-Kit/commit/f6838f00c8ada41c548effbff1b89bf341e5f97c

**Comment by philmmanjaro** [comment]
@codesardine Seems this still doesn't work:

```
ms-office-online/usr/bin $ ls -l .
insgesamt 0
lrwxrwxrwx 1 phil phil 43 22. Apr 07:47 ms-excel -> /usr/share/ms-office/excel/ms-office-online
lrwxrwxrwx 1 phil phil 44 22. Apr 07:47 ms-office -> /usr/share/ms-office/office/ms-office-online
lrwxrwxrwx 1 phil phil 45 22. Apr 07:47 ms-onenote -> /usr/share/ms-office/onenote/ms-office-online
lrwxrwxrwx 1 phil phil 45 22. Apr 07:47 ms-outlook -> /usr/share/ms-office/outlook/ms-office-online
lrwxrwxrwx 1 phil phil 48 22. Apr 07:47 ms-powerpoint -> /usr/share/ms-office/powerpoint/ms-office-online
lrwxrwxrwx 1 phil phil 43 22. Apr 07:47 ms-skype -> /usr/share/ms-office/skype/ms-office-online
lrwxrwxrwx 1 phil phil 42 22. Apr 07:47 ms-word -> /usr/share/ms-office/word/ms-office-online
```

```
$ ms-office
Identifying User Agent as - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Safari/605.1.15
Traceback (most recent call last):
  File "/usr/bin/ms-office", line 53, in <module>
    applicationWindow()
  File "/usr/bin/ms-office", line 49, in __init__
    self.webview.load_uri(settings("app", "route"))
TypeError: Argument 1 does not allow None as a value
phil@development ~/dev/git/manjaro/repositories/stable-repos/community/ms-office-online $ pacman -Q python-jade-application-kit
python-jade-application-kit 1.3.3-1
```
I assume the laucher script needs still to be modified ...

**Comment by codesardine** [comment]
I know it is not ideal but for now a bash script pointing to /usr/share/ms-office/excel/ms-office-online does the job is working on my end, until i have a better way of doing settings. 

```
else:
                    # use existing office settings.json
                    os.chdir("/usr/share/ms-office/msoffice/")
                    # open url in a new window
                    subprocess.call(["jak", url])
```
this block of code above works as intended.
JAK when using https sets windows icons and titles from the URL  

My proposal remove everything from "same_frame"  in settings.json", leave only office/office365 there
anything that is not office will open in a separate window like it is a separate application.

For example i am working on Office and want to check my mail the way is setup now when I click on outlook Office goes to the outlook link and i cant work on office anymore.

Have a go on your end, play with it for a bit and click the links so you can understand how it works with my setup.

"same_frame": ["https://office.live.com", "https://www.office.com", "office365"]  <- Office
"same_frame": ["https://www.onenote.com"] <- onenote
"same_frame": ["https://www.skype.com"] <- skype

**Comment by codesardine** [comment]
Update - Makefile

 Outlook:
New user agent needed to force display of new UI

```
"user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14",
"same_frame": ["https://people.live.com", "https://calendar.live.com"]
```
Office, Word, Excel, Powerpoint
```
"same_frame": ["https://office.live.com", "https://www.office.com"]
```

**Comment by codesardine** [comment]
I think we can close this one, everything is working on my end, unless you want to add something? @philmmanjaro

**Comment by codesardine** [comment]
Closing this one if anything else is needed open a new issue @philmmanjaro
